repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. If bumping this, please also bump requirements-dev.in
    rev: v0.8.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          [
            "--disable-plugin",
            "HexHighEntropyString",
            "--disable-plugin",
            "Base64HighEntropyString",
          ]
        exclude: tests/keys/rsa256
  # djLint moved in from assess - to apply as a precommit hook we should make sure it works with
  # apply templates
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.3
    hooks:
      - id: djlint-jinja
        types_or: ["html", "jinja"]
