[package]
name = "funding-service-design-authenticator"
version = "0.1.1"
description = "The funding service design authenticator for the DLUHC."
authors = ["Version One"]
license = "MIT License"

[tool.black]
line-length = 120
experimental-string-processing = 1

[tool.flake8]
max-line-length = 120
count = true
