name: Deploy to Gov PaaS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  test_and_deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/deploy.yml@fs-2415-standardise-github-workflows
    with:
      app_name: ${{ github.event.repository.name }}
      api: false
      assets_required: true
      postgres_unit_testing: true
      include_rsa256_base64: true
      include_forms_service_private_host: true
      include_sentry_dsn: true
      include_rsa256_base64_private: true
      include_azure_ad_client_id: true
      include_azure_ad_tenant_id: true
      include_azure_ad_client_secret: true
      include_secret_key: true
      include_session_cookie_name: true
      deploy_to_dev: true
      apply_network_policy: true
      users: 2
      spawn-rate: 2
      run_performance_tests: true
      run_e2e_tests: true
    secrets:
      CF_API: ${{secrets.CF_API}}
      CF_ORG: ${{secrets.CF_ORG}}
      CF_SPACE: ${{secrets.CF_SPACE}}
      CF_USER: ${{secrets.CF_USERNAME}}
      CF_PASSWORD: ${{secrets.CF_PASSWORD}}
      E2E_PAT: ${{secrets.E2E_PAT}}
      RSA256_PUBLIC_KEY_BASE64: ${{secrets.RSA256_PUBLIC_KEY_BASE64}}
      FORMS_SERVICE_PRIVATE_HOST: ${{secrets.FORMS_SERVICE_PRIVATE_HOST}}
      SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      RSA256_PRIVATE_KEY_BASE64: ${{secrets.RSA256_PRIVATE_KEY_BASE64}}
      AZURE_AD_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
      AZURE_AD_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      SESSION_COOKIE_NAME: ${{secrets.SESSION_COOKIE_NAME}}
