name: Deploy to Gov PaaS

on:
  workflow_dispatch:
    inputs:
      environment:
        description:  Which AWS Account to use
        type: choice
        required: true
        options:
        - test
        - uat
      deploy_to_dev:
        required: false
        default: false
        type: boolean
        description: Deploy to CloudFoundry dev?
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  test_and_deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/deploy.yml@main
    with:
      app_name: ${{ github.event.repository.name }}
      assets_required: true
      deploy_to_dev: true
      apply_network_policy: true
      run_performance_tests: true
      run_e2e_tests: true
      include_manifest: true
    secrets:
      CF_API: ${{secrets.CF_API}}
      CF_ORG: ${{secrets.CF_ORG}}
      CF_SPACE: ${{secrets.CF_SPACE}}
      CF_USER: ${{secrets.CF_USERNAME}}
      CF_PASSWORD: ${{secrets.CF_PASSWORD}}
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
      RSA256_PUBLIC_KEY_BASE64: ${{secrets.RSA256_PUBLIC_KEY_BASE64}}
      RSA256_PRIVATE_KEY_BASE64: ${{secrets.RSA256_PRIVATE_KEY_BASE64}}
      AZURE_AD_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
      AZURE_AD_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      SESSION_COOKIE_NAME: ${{secrets.SESSION_COOKIE_NAME}}
