name: Tag-zip release
permissions:
  contents: write
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-prerelease

    paths-ignore:
      - '**/README.md'

jobs:
  tag-to-release:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/tag-to-release.yml@main
    with:
      build_static_assets: true
  paketo_build:
    needs: tag-to-release
    permissions:
      packages: write
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/package.yml@main
    with:
      version_to_build: ${{ needs.tag-to-release.outputs.new_tag }}
      owner: ${{ github.repository_owner }}
      application: funding-service-design-authenticator
      assets_required: true
